### PR TITLE
fix(server): :goal_net: Send a 404 when using outdated getContentById API.

### LINKED ISSUE #2142: Graceful fallback for old /dispositifs/getContentById route
Currently mobile apps which haven't been updated can still call this endpoint resulting in a 500 error.

### PR DESCRIPTION
**Pull request by kaaloo**
- added check for getContentById route to ensure more graceful failure
- added vscode setting to use relative imports with auto import

Fixes: #2142

### CODE REVIEW

File: server/src/controllers/dispositifController.ts [hunk 1]
```diff
@@ -30,8 +28,13 @@ import {
   StructureReceiveDispositifRequest,
   UpdateDispositifPropertiesRequest,
   UpdateDispositifRequest,
-  UpdateDispositifResponse,
-} from "@refugies-info/api-types";
+  UpdateDispositifResponse
+} from "@refugies-info/api-types"
+import express from "express"
+import { NotFoundError } from "src/errors"
```
Comment (matthieu-fesselier) [inline server/src/controllers/dispositifController.ts]: I think this will throw an error on deployment, we need to use the relative path instead. 
Locally, it works fine with `npm run dev`, but if we do `npm run tsc && npm run start`, it does not work

**Review by matthieu-fesselier — CHANGES_REQUESTED** [review]

File: server/src/controllers/dispositifController.ts (hunk 1 above)
Comment (kaaloo) [reply server/src/controllers/dispositifController.ts]: Awesome  catch @matthieu-fesselier !  🙏🏼

**Review by matthieu-fesselier — APPROVED** [review]
great, works fine with me!
